#!/bin/bash

# Check if the script is being run as root
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
fi

# Create a symbolic link to the script passed as argument in /usr/local/bin
ln -s "$(pwd)/$1" /usr/local/bin/$1
chmod +x /usr/local/bin/$1
